name: build_and_test

on:
  push:
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get sample repo
        uses: actions/checkout@v2
        with: 
          repository: gregdelozier/sample-repo

      - name: Copy files to server
        run: |
           ls -la
           pip install pytest
           pytest test_mathstuff.py
