name: deploy to https://walshbouncer.pythonanywhere.com

on:
  push:
  # workflow_dispatch:

# ENVIRONMENT DEFINITION

env:
  # target
  HOST: ssh.pythonanywhere.com
  USER: walshbouncer

  # global options
  SSH_OPTIONS: -i ~/.ssh/id_rsa -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

# JOB TASKS

jobs:
  deploy_to_https_server:
    runs-on: ubuntu-latest
    steps:

      # INSTALL SSH KEY
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_RSA_WALSH }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Get sample repo
        uses: actions/checkout@v2
        with: 
          repository: gregdelozier/sample-repo

      - name: Copy files to server
        run: |
          echo ${{ secrets.ID_RSA_WALSH }}

      # - name: Copy files to server
      #   run: |
      #     export TARGET=$USER@$HOST
      #     export RUN="ssh $SSH_OPTIONS $TARGET"
      #     export COPY="scp $SSH_OPTIONS"

      #     # ls -la $GITHUB_WORKSPACE
      #     $RUN 'ls -la'
      #     $RUN 'pwd'
      #     $RUN 'whoami'
      #     # $RUN 'cd mysite ; git pull'
      #     echo $COPY $GITHUB_WORKSPACE/index.html $TARGET:/home/walshbouncer/mysite
      #     $COPY $GITHUB_WORKSPACE/index.html $TARGET:/home/walshbouncer/mysite
      #     echo $COPY $GITHUB_WORKSPACE/sketch.js $TARGET:/home/walshbouncer/mysite
      #     $COPY $GITHUB_WORKSPACE/sketch.js $TARGET:/home/walshbouncer/mysite
      #     echo $COPY $GITHUB_WORKSPACE/style.css $TARGET:/home/walshbouncer/mysite
      #     $COPY $GITHUB_WORKSPACE/style.css $TARGET:/home/walshbouncer/mysite
          
