name: Say hello

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
  
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment files
        uses: actions/checkout@v2
      - name: Run some example commands
        run: |
          echo Hello!
          ls -la 
          pwd
          whoami
          echo "-la /home/runner/work/sample-repo/sample-repo"
          ls -la /home/runner/work/sample-repo/sample-repo
          echo "$ df -h ."
          df -h .
          # echo "$ top -n 1"
          # top -n 1
      - name: Check the packages
        run: |
          pip freeze
      - name: Test the code
        run: |
          python3 hello.py
      - name: Check on node
        run: |
          node --version
          node hello.js

