name: Say hello

on:
  workflow_dispatch:
  
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Verify presence of files
        run: |
          echo Hello!
          ls -la 
          pwd
          whoami
          echo "-la /home/runner/work/sample-repo/sample-repo"
          ls -la /home/runner/work/sample-repo/sample-repo
          echo "$ df ."
          df .
          echo "$ top -n 1"
          top -n 1
      